---
# This shouldn't be necessary
# Ref: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/3481#issuecomment-44648280
- name: "prereqs-ccs : Pre-create CCS ServiceAccounts with the right ImagePullSecret"
  kubernetes.core.k8s:
    apply: yes
    template: templates/ccs/serviceAccounts.yml.j2
