---
# 0. Lookup the version and flavour of OCP that we are targeting
# -----------------------------------------------------------------------------
# In Frye OCP 4.6 we find this configmap named as "openshift-install-manifests"
# In ROKS OCP 4.6 and 4.8 we find this configmap named as "openshift-install"

- name: Get OCP Install Information (openshift-install)
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: openshift-install
    namespace: openshift-config
  register: openshift_config

- name: Register OCP install configuration variables (openshift-install)
  when:
    - openshift_config.resources is defined
    - openshift_config.resources | length > 0
  set_fact:
    ocp_install_invoker: "{{ openshift_config.resources[0].data.invoker }}" # Known values: "ROKS"
    ocp_install_version: "{{ openshift_config.resources[0].data.version }}"
    ocp_install_release: "{{ openshift_config.resources[0].data.version | regex_search('[^.]*.[^.]*') }}"

# If we didn't already set the new facts then it means we couldn't find the "openshift-install" configmap
- name: Get OCP Install Information (openshift-install-manifests)
  when: ocp_install_invoker is not defined
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: openshift-install-manifests
    namespace: openshift-config
  register: openshift_config

- name: Register OCP install configuration variables (openshift-install-manifests)
  when:
    - ocp_install_invoker is not defined
    - openshift_config.resources is defined
    - openshift_config.resources | length > 0
  set_fact:
    ocp_install_invoker: "{{ openshift_config.resources[0].data.invoker }}" # Known values: "user" (in Fyre)
    ocp_install_version: "{{ openshift_config.resources[0].data.version }}"
    ocp_install_release: "{{ openshift_config.resources[0].data.version | regex_search('[^.]*.[^.]*') }}"

# If we didn't already set the new facts then it means we couldn't find either of the expected configmaps
- name: Fail if we couldn't find the openshift-install or openshift-install-manifests configmaps
  assert:
    that: ocp_install_invoker is defined
    fail_msg: "We couldn't find either the openshift-install or openshift-install-manifests configmaps in the openshift-config namespace"

- name: Debug OCP install configuration variables
  debug:
    msg:
      - "OCP Install Invoker ................ {{ ocp_install_invoker }}"
      - "OCP Install Version ................ {{ ocp_install_version }}"
      - "OCP Install Release ................ {{ ocp_install_release }}"


# 1. Install Service Binding Operator
# -----------------------------------------------------------------------------
# Install stable channel with automatic updates if MAS 8.7+, otherwise, install preview channel locked to v0.8
# Unless MAS Channel = 8.8.x, in which case we don't need SBO anymore
- name: Define which SBO to install
  when: mas_channel != "8.8.x"
  set_fact:
    sbo_channel: "{{ 'stable' if (mas_channel not in mas_channels_old_releases and ocp_install_release != '4.6') else 'preview' }}"

- name: "Launch SBO install"
  when: mas_channel != "8.8.x"
  include_tasks: "tasks/install/{{ sbo_channel }}.yml"
