---

# 1. Check for MAS ImageContentSourcePolicy
# -----------------------------------------------------------------------------
- name: "Determine whether this is an airgap environment"
  include_tasks: "{{ role_path }}/../../common_tasks/detect_airgap.yml"


# 2. Install IBM catalogs
# -----------------------------------------------------------------------------
# In an airgap install scenario, the catalogs are already installed as part of
# preparing the cluster
- name: "Create IBM catalogs"
  when:
    - not airgap_install
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/ibm-catalogs.yml') }}"

- name: "Wait till IBM Catalogs are Ready"
  when:
    - not airgap_install
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: CatalogSource
    name: "{{ item }}"
    namespace: openshift-marketplace
  register: ibm_catalog_lookup
  retries: 30 # Up to 30 min
  delay: 60 # Every minute
  until:
    - ibm_catalog_lookup.resources is defined
    - ibm_catalog_lookup.resources | length == 1
    - ibm_catalog_lookup.resources[0].status is defined
    - ibm_catalog_lookup.resources[0].status.connectionState is defined
    - ibm_catalog_lookup.resources[0].status.connectionState.lastObservedState is defined
    - ibm_catalog_lookup.resources[0].status.connectionState.lastObservedState == "READY"
  with_items:
    - ibm-operator-catalog
    - opencloud-operators

# 3. Install development (pre-release) catalogs
# -----------------------------------------------------------------------------
# In an airgap install scenario, the catalogs are already installed as part of
# preparing the cluster
- name: "Install development (pre-release) catalogs"
  when:
    - artifactory_username is defined and artifactory_username != ""
    - artifactory_apikey is defined and artifactory_apikey != ""
    - not airgap_install
  include_tasks: "tasks/development-catalogs.yml"
