---
# 1. Wait for CP4D service CR to be ready
# -----------------------------------------------------------------------------
- name: "wait-wd : Wait for watsonDiscoveryStatus 'Completed' (5m interval)"
  kubernetes.core.k8s_info:
    api_version: "{{ cpd_service_info[cpd_service_name].api_version }}"
    kind: "{{ cpd_service_info[cpd_service_name].crd_kind }}"
    name: "{{ cpd_service_info[cpd_service_name].cr_name }}"
    namespace: "{{ cpd_instance_namespace }}"
  register: cpd_cr_lookup
  until:
    - cpd_cr_lookup.resources is defined
    - cpd_cr_lookup.resources | length == 1
    - cpd_cr_lookup.resources[0].status is defined
    - cpd_cr_lookup.resources[0].status.watsonDiscoveryStatus is defined
    - cpd_cr_lookup.resources[0].status.watsonDiscoveryStatus == "Completed"
  retries: 66 # Up to 5.5 (yes, FIVE !!) hours
  delay: 300 # Every 5 minutes
