---

# 1. Wait for CP4D service CR to be ready
# -----------------------------------------------------------------------------
- name: "wait-dods : Wait for dodsStatus 'Completed' or 'Failed' (2m interval)"
  kubernetes.core.k8s_info:
    api_version: "{{ cpd_service_info[cpd_service_name].api_version }}"
    kind: "{{ cpd_service_info[cpd_service_name].crd_kind }}"
    name: "{{ cpd_service_info[cpd_service_name].cr_name }}"
    namespace: "{{ cpd_instance_namespace }}"
  register: cpd_cr_lookup
  until:
    - cpd_cr_lookup.resources is defined
    - cpd_cr_lookup.resources | length == 1
    - cpd_cr_lookup.resources[0].status is defined
    - cpd_cr_lookup.resources[0].status.dodsStatus is defined
    - cpd_cr_lookup.resources[0].status.dodsStatus == "Completed" or cpd_cr_lookup.resources[0].status.dodsStatus == "Failed"
  retries: 30 # Up to 1 hour
  delay: 120 # Every 2 minutes

- name: "wait-dods : Check that the Decision Optimization dodsStatus is 'Completed'"
  assert:
    that: cpd_cr_lookup.resources[0].status.dodsStatus == "Completed"
    fail_msg: "Decision Optimization (dods) install failed (dodsStatus)"
