---
# Add Manage 8.3.x application to an existing MAS Core 8.7.x installation
#
# Dependencies:
# - ansible-playbook ibm.mas_devops.oneclick_core
#
- hosts: localhost
  any_errors_fatal: true

  vars:
    # Application Dependencies
    db2_instance_name: "{{ lookup('env', 'DB2_INSTANCE_NAME') | default('db2w-shared', true) }}"

    # Application Installation
    # mas_app_id can be set to "health" to install manage in the "Health standalone" mode from this same playbook.
    mas_app_id: "{{ lookup('env', 'MAS_APP_ID') | default('manage', true) }}"
    mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') | default('8.3.x', true) }}"

    # Application Configuration
    mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') | default('masdev', true) }}"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
          - lookup('env', 'MAS_INSTANCE_ID') != ""
          - lookup('env', 'MAS_CONFIG_DIR') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.db2
    - ibm.mas_devops.suite_db2_setup_for_manage
    - ibm.mas_devops.suite_config
    - ibm.mas_devops.suite_app_install
    - ibm.mas_devops.suite_app_config
