---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if mas_instance_id is not provided"
  assert:
    that: mas_instance_id is defined and mas_instance_id != ""
    fail_msg: "mas_instance_id property is required"


# 2. Set up the domain name for MAS
# -----------------------------------------------------------------------------
- name: "Get cluster subdomain"
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: _cluster_subdomain

- name: "Configure domain if not set"
  when: mas_domain == ""
  set_fact:
    mas_domain: "{{ mas_instance_id }}.{{ _cluster_subdomain.resources[0].spec.domain }}"


# 3. Determine version of cert-manager in use on the cluster
# -----------------------------------------------------------------------------
- include_tasks: tasks/detect-cert-manager.yml


# 4. Provide debug information
# -----------------------------------------------------------------------------
- name: "Configure namespace"
  set_fact:
    mas_namespace: "mas-{{ mas_instance_id }}-core"

- name: "Debug information"
  debug:
    msg:
      - "Catalog source ............... {{ mas_catalog_source }}"
      - "MAS channel .................. {{ mas_channel }}"
      - "Instance ID .................. {{ mas_instance_id }}"
      - "MAS namespace ................ {{ mas_namespace }}"
      - "MAS domain ................... {{ mas_domain }}"
      - "MAS ICR cp content ........... {{ mas_icr_cp }}"
      - "MAS ICR cpopen content ....... {{ mas_icr_cpopen }}"
      - "MAS Cluster Issuer ........... {{ mas_cluster_issuer }}"
      - "MAS Subcription Upgrade ...... {{ mas_upgrade_strategy }}"


# 5. Install the operator & create entitlement secret
# -----------------------------------------------------------------------------
- name: "Install MAS Operator"
  include_role:
    name: ibm.mas_devops.install_operator
  vars:
    namespace: "{{ mas_namespace }}"
    icr_host: "{{ mas_icr_cp }}"
    icr_username: "{{ mas_entitlement_username }}"
    icr_password: "{{ mas_entitlement_key }}"
    catalog_source: "{{ mas_catalog_source }}"
    operator_group: "{{ lookup('template', 'templates/operator-group.yml.j2') }}"
    subscription: "{{ lookup('template', 'templates/subscription.yml.j2') }}"

- name: Lookup and Approve MAS Subscription
  when: mas_upgrade_strategy == 'Manual'
  block:
    - name: Lookup Operator install plan
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: InstallPlan
        namespace: "{{ mas_namespace }}"
        label_selectors:
          - "operators.coreos.com/ibm-mas.{{ mas_namespace }}"
      register: mas_install_plan
      retries: 20
      delay: 60 # Retry for approx 20 minutes (60s * 20 attempts) before giving up
      until: mas_install_plan.resources | length > 0

    - name: Approve the subscription install plan
      when:
        - mas_install_plan.resources | length > 0
        - mas_install_plan.resources[0].status.phase != "Complete"
      kubernetes.core.k8s:
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: InstallPlan
          metadata:
            name: "{{ mas_install_plan.resources[0].metadata.name }}"
            namespace: "{{ mas_namespace }}"
          spec:
            approved: true


# 6. Wait until the Suite CRD is available
# -----------------------------------------------------------------------------
- name: "Wait until the Suite CRD is available"
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    name: "suites.core.mas.ibm.com"
    kind: CustomResourceDefinition
    wait: yes
    wait_sleep: 10
    wait_timeout: 300 # 5 mins until we give up waiting for the CRD to get into the expected state
    wait_condition:
      type: NamesAccepted
      status: "True"
  register: suite_crd_info
  retries: 120 # ~approx 5 minutes before we give up waiting for the CRD to be created
  delay: 5 # seconds
  until:
    - suite_crd_info.resources is defined
    - suite_crd_info.resources | length > 0


# 7. Integrated Airgap support
# -----------------------------------------------------------------------------
# Before we create the CR we will set up the Airgap Image Map
# We need to install the digest imagemap for ibm-sls and ibm-truststore-mgr
- name: "Determine whether this is an airgap environment"
  include_tasks: "{{ role_path }}/../../common_tasks/detect_airgap.yml"

- name: "Enable use of image digests"
  when: airgap_install
  include_tasks: "tasks/install_digest_cm.yml"


# 8. Suite installation
# -----------------------------------------------------------------------------
- name: Create suite.ibm.com/v1 CR
  vars:
    annotation_dict: "{{ mas_annotations | string | ibm.mas_devops.getAnnotations() }}"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ mas_namespace }}"
    template: templates/core_v1_suite.yml.j2


# 9. Handle IBM Common Services Install plan approvals when upgrade strategy is set to Manual
# -----------------------------------------------------------------------------
# ibm-common-services operators deployed by MAS will inherit the inherit MAS upgrade strategy
# when its set to Manual, we need to interate those to ensure we do approve the first install plan
# otherwise MAS installation wont succeed.
- include_tasks: tasks/ibm-common-services.yml
  when: mas_upgrade_strategy == 'Manual'
  loop: "{{ibm_common_services_subscription_labels}}"
