---

# cluster_name has no default, it must be passed in
cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"

# cluster_type has no default, it must be passed in
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE')}}"

# What cluster types does this role support
supported_cluster_types:
  - fyre
  - roks
  - rosa
  - ipi

# ROKS
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"

# ROSA
rosa_token: "{{ lookup('env', 'ROSA_TOKEN') }}"

# Fyre
fyre_username: "{{ lookup('env', 'FYRE_USERNAME') }}"
fyre_apikey: "{{ lookup('env', 'FYRE_APIKEY') }}"

# AWS
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

# IPI
ipi_dir: "{{ lookup('env', 'IPI_DIR') | default(ansible_env.HOME ~ '/openshift-install', True) }}"
ocp_installer_dir: "{{ ipi_dir }}/{{ ocp_version }}"
ocp_installer_exe: "{{ ipi_dir }}/{{ ocp_version }}/openshift-install"
ipi_config_dir: "{{ ipi_dir }}/config/{{ cluster_name }}"
