---
# --- MAS channel control ---------------------------------------------------------------------------------------------
# Temporary solution: this will be used to determine whether to install SBO stable channel and the IBM badged cert-manager
# all other channels will install SBO from the stable channel and the IBM Cert Manager (foundation services)
# By default will we assume that we are installing for the latest minor channel (currently 8.8.x)
mas_channel: "{{ lookup('env', 'MAS_CHANNEL') | default('8.8.x', True)}}"
mas_channels_old_releases: ['8.6.x', '8.5.x']
