---
# Dev Catalog Settings
# -----------------------------------------------------------------------------
# Only required when using the development catalog sources for pre-release installation
# These are used to set up image pull secret in the openshift-marketplace namespace
#
# They will also be added to the ibm-entitlement image pull secret, this allows released
# versions of operators to be mixed with development versions of dependencies (e.g. truststore manager)
artifactory_username: "{{ lookup('env', 'ARTIFACTORY_USERNAME') | lower }}"
artifactory_apikey: "{{ lookup('env', 'ARTIFACTORY_APIKEY') }}"
