---
# Db2 backup default vars
db2_backup_dir: "{{ lookup('env', 'DB2_BACKUP_DIR') }}"
db2_backup_instance_name: "{{ lookup('env', 'DB2_BACKUP_INSTANCE_NAME') }}"
db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') | default('db2u', true) }}"

# Temporary vars to be used during backup process in db2 engine pod
db2_temp_backup_dir: /mnt/backup/db_backup
db2_db2inst1_backup_dir: /mnt/blumeta0/home/db2inst1/db_backup
db2_keystore_dir: /mnt/blumeta0/db2/keystore
