---

# cluster_name has no default, it must be passed in
cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"

# cluster_type has no default, it must be passed in
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE')}}"

#default value for cluster_platform is x for x86 cluster, if any other arch is to be specified it must be passed in
cluster_platform: "{{lookup('env', 'CLUSTER_PLATFORM') | default('x',true)}}"

# We can't provide a default, there is no single value that would make sense across all providers, and that would not eventually become dated
ocp_version: "{{ lookup('env', 'OCP_VERSION') }}"

# GPU node settings
# Flag to add GPU worker node to cluster. Currently only set up for ROKS clusters
ocp_provision_gpu: "{{ lookup('env', 'OCP_PROVISION_GPU') | default('false', True) }}"

# The number of GPU worker nodes to deploy. Currently only set up for ROKS clusters
gpu_workers: "{{ lookup('env', 'GPU_WORKERS') | default('1', true) }}"

# The name of the gpu worker pool.
gpu_workerpool_name: "{{ lookup('env', 'GPU_WORKERPOOL_NAME') | default('gpu', true) }}"

# What cluster types does this role support
supported_cluster_types:
  - fyre
  - roks
  - rosa

# ROKS defaults
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
ibmcloud_resourcegroup: "{{ lookup('env', 'IBMCLOUD_RESOURCEGROUP') | default('Default', true) }}"

roks_zone: "{{ lookup('env', 'ROKS_ZONE') | default('dal10', true) }}"
roks_flavor: "{{ lookup('env', 'ROKS_FLAVOR') | default('b3c.16x64.300gb', true) }}"
roks_workers: "{{ lookup('env', 'ROKS_WORKERS') | default('3', true) }}"
roks_flags: "{{ lookup('env', 'ROKS_FLAGS') | default('', true) }}"

# FYRE defaults
fyre_username: "{{ lookup('env', 'FYRE_USERNAME') }}"
fyre_password: "{{ lookup('env', 'FYRE_APIKEY') }}"

fyre_cluster_description: "{{ lookup('env', 'FYRE_CLUSTER_DESCRIPTION') | default('No description provided', true) }}"
fyre_cluster_size: "{{ lookup('env', 'FYRE_CLUSTER_SIZE') | default('large', true) }}"
fyre_product_id: "{{ lookup('env', 'FYRE_PRODUCT_ID') }}"
fyre_quota_type: "{{ lookup('env', 'FYRE_QUOTA_TYPE') | default('quick_burn', true) }}"

# Only used when quota_type == product_group
fyre_worker_count: "{{ lookup('env', 'FYRE_WORKER_COUNT') | default('3', true) }}"
fyre_worker_memory: "{{ lookup('env', 'FYRE_WORKER_MEMORY') | default('16', true) }}"
fyre_worker_cpu: "{{ lookup('env', 'FYRE_WORKER_CPU') | default('64', true) }}"

# ROSA defaults
rosa_token: "{{ lookup('env', 'ROSA_TOKEN') }}"
rosa_cluster_admin_password: "{{ lookup('env', 'ROSA_CLUSTER_ADMIN_PASSWORD') }}"
rosa_compute_nodes: "{{ lookup('env', 'ROSA_COMPUTE_NODES') | default('3', true) }}"
