---
# Db2 restore default vars
db2_restore_dir: "{{ lookup('env', 'DB2_RESTORE_DIR') }}"
db2_restore_instance_name: "{{ lookup('env', 'DB2_RESTORE_INSTANCE_NAME') }}"
db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') | default('db2u', true) }}"
db2_dbname: "{{ lookup('env', 'DB2_DBNAME') | default('BLUDB', true) }}"

# Temporary vars to be used during restore process in db2wh pod
db2_temp_backup_dir: /mnt/backup/db_backup
db2_db2inst1_backup_dir: /mnt/backup/db_backup #/mnt/blumeta0/home/db2inst1/db_backup
db2_temp_backup_logs_dir: /mnt/backup/db_backup_logs
