---
# MAS configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

# MAS application configuration
mas_app_id: "{{ lookup('env', 'MAS_APP_ID') }}"
mas_appws_jdbc_binding: "{{ lookup('env', 'MAS_APPWS_JDBC_BINDING') }}"
mas_appws_components: "{{ lookup('env', 'MAS_APPWS_COMPONENTS') | ibm.mas_devops.appws_components | default('{}', true) }}"
mas_app_ws_spec: "{{ lookup('env', 'MAS_APP_WS_SPEC') }}"
